version: "3.9"
services:
  postgres:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "1111:5432"