spring:
  datasource:
    url: jdbc:postgresql://localhost:1111/test
    username: test
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: file:C:\Docs\Java Projects\idfLAB-banking-api\common-resources\db\changelog\db.changelog-master.yaml
